server:
  port: 9000
  shutdown: graceful                    # 우아한 종료를 위한 활성화
  netty:
    connection-timeout: 2s              # 서버와 TCP 연결을 수립하기 위해 기다리는 시간
    idle-timeout: 15s                   # 데이터가 전송되지 않는 경우 TCP 연결을 닫기 전에 기다리는 시간

spring:
  application:
    name: cns-edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s     # 15초간의 우아한 종료기간을 둔다
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000           # 연결을 수립하기까지의 타임아웃(밀리초)
        response-timeout: 5s            # 응답을 받을때까지의 타임아웃
        pool:
          type: elastic                 # 연결 풀 유형 (elastic, fixed, disable 중 하나)
          max-idle-time: 15s            # 클라이언트가 서버에 요청을 보내지 않는 상태에서 연결을 유지할 수 있는 최대 시간
          max-life-time: 60s            # 클라이언트가 서버와 연결된 후 유지될 수 있는 최대 시간. 해당 시간이 지나면 연결은 강제로 종료됨.
      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books   # URI 값은 환경변수로 오거나 해당 환경변수가 없는 경우 오른쪽의 기본값을 사용한다
          predicates:
            - Path=/books/**            # 일치하는 경로를 술어로 사용한다
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
          predicates:
            - Path=/orders/**